### ISSUE TITLE
Plugin version not updated for v0.4.0

### ISSUE THREAD

**Issue by stephan2012** [helm/helm-mapkubeapis#101]
The `plugin.yaml` still shows v0.3.2:

```yaml
plugin.yaml 
name: "mapkubeapis"
version: "0.3.2"
usage: "Map release deprecated Kubernetes APIs in-place"
description: "Map release deprecated Kubernetes APIs in-place"
command: "$HELM_PLUGIN_DIR/bin/mapkubeapis"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
```

This causes a `helm plugin ls` to show a wrong version number.
