### ISSUE TITLE
Support for non-Kubernetes APIs

### ISSUE THREAD

**Issue by stephan2012** [helm/helm-mapkubeapis#55]
Today, I was facing an error message after upgrading the [Kubernetes cert-manager](https://github.com/jetstack/cert-manager) from version 1.5.4 to 1.6.1 when deploying an application update via Helm:

```text
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha3"
helm.go:88: [debug] unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha3"
current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes
```

Okay, cert-manager removed the alpha and beta APIs, so I expected their absence. The [Helm docs](https://helm.sh/docs/topics/kubernetes_apis/) recommend updating charts before actually removing APIs, but that sometimes is out of my control. Also, it can put me in a kind of chicken-and-egg situation where I need to have a dependency already present in the cluster before I can update a Helm release.

Luckily, `helm-mapkubeapis` to the rescue! I have added

```yaml
  - deprecatedAPI: "apiVersion: cert-manager.io/v1alpha1\nkind: Certificate"
    newApi: "apiVersion: cert-manager.io/v1\nkind: Certificate"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: cert-manager.io/v1alpha2\nkind: Certificate"
    newApi: "apiVersion: cert-manager.io/v1\nkind: Certificate"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: cert-manager.io/v1alpha3\nkind: Certificate"
    newApi: "apiVersion: cert-manager.io/v1\nkind: Certificate"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: cert-manager.io/v1beta1\nkind: Certificate"
    newApi: "apiVersion: cert-manager.io/v1\nkind: Certificate"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
```

to a Mapfile and ran `helm mapkubeapis`, which worked as expected (or hoped?). So, the actual issue is technically solved for me.

The only thing left (and reason to raise this issue) is that `helm-mapkubeapis` refers to Kubernetes versions in `deprecatedInVersion` and `removedInVersion` while the API discussed here is a CRD served by the Kubernetes cert-manager. So, I wonder if there is a sound way to track API versions and deprecations from 3rd party providers and their versioning instead of Kubernetes.

**Comment by hickeyma** [comment]
Thank you for raising this @stephan2012. I am glad that you were able to get it working for you.

> The only thing left (and reason to raise this issue) is that helm-mapkubeapis refers to Kubernetes versions in deprecatedInVersion and removedInVersion while the API discussed here is a CRD served by the Kubernetes cert-manager. So, I wonder if there is a sound way to track API versions and deprecations from 3rd party providers and their versioning instead of Kubernetes.

Not sure how you would handle custom resources like this as they are not specifically tied to the Kubernetes version and differ between CRD version.

**Comment by stephan2012** [comment]
That’s exactly the point. If there’s any reliable way to discover the API provider and its version, the constraints could be enriched by something like

```yaml
  - deprecatedAPI: "apiVersion: cert-manager.io/v1beta1\nkind: Certificate"
    newApi: "apiVersion: cert-manager.io/v1\nkind: Certificate"
    deprecatedInProviderVersion: "v1.5.0"
    removedInProviderVersion: "v1.6.0"
```

It would even be beneficial if the API provider has to be named explicitly in the Map file. I currently do not know if the Kubernetes API server tracks the required data.

Having such a mechanism would help not only for cert-manager, but for many other operators defining CRDs (e.g., Rook, Postgres Operator, ECK, …).
