### ISSUE TITLE
Substring APIs are matched too agressively using the default config

### ISSUE THREAD

**Issue by pgier** [helm/helm-mapkubeapis#56]
I have a Helm config which contains deprecated instances of both
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
```
and
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
```

_Edit: The default mapping contains "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRole" which matches/replaces both of the above types.  And when the plugin checks for ClusterRoleBinding, it doesn't find any because they have already been replaced by the previous match._

So I was confused when running a `dry-run` and mapkubeapis was only finding `ClusterRole` and not `ClusterRoleBinding`.
Digging into the code, I found the reason for this is because `ClusterRole` is a substring of `ClusterRoleBinding` and all instances of `ClusterRoleBinding` had been replaced before it was checked.  In this case this is only an issue of CLI output, and the resulting helm manifest ends up the same either way.  However, I can see a situation where this could cause a problem where you want to upgrade one kind but not the other.

Some possible fixes would be to:
(1) Change the order of matches in the default config so that longer kinds come first
(2) add newline characters at the end of all the map strings in the mapping config
(3) use a regex instead of strings.Replace() which matches the strings more strictly with maybe any whitespace at the end

**Comment by hickeyma** [comment]
Thanks for raising this @pgier. I tried to reproduce this but was unable initially. Then I stumbled across an example template I used for ClusterRoleBinding as follows:

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
[...]
```

In this scenario the default mapping file entry will no find it.  The entry needs to be tweaked as follows because of the comment:

```yaml
- deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\n# This cluster role binding allows anyone in the \"manager\" group to read secrets in any namespace.\nkind: ClusterRoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
```

It works then as expected.

Do you think that this maybe something similar to what you found?
